### ISSUE TITLE
orig_data_size: no such file or directory - with klernel 4.19.x

### ISSUE THREAD

**Issue by sedimentation-fault** [rdiez/Tools#1]
It seems that _zram_ has changed its exposed interface under _/sys/devices/virtual/block/_: my two zram devices, _zram0_ and _zram1_, lack variables like _orig_data_size_, so that I get

`zram-stats: line 178:  /sys/devices/virtual/block/zram1/orig_data_size: no such file or directory`

(I've added a few comments and renamed the script to zram-stats, so name and line numbers differ a bit from the original).

**Reason**

The variables used by the script

```
$ZRAM_DIR/orig_data_size
$ZRAM_DIR/compr_data_size
$ZRAM_DIR/mem_used_total
$ZRAM_DIR/zero_pages
```

are missing in ZRAM_DIR=/sys/devices/virtual/block/zram*. I use kernel 4.19.19 - but I had the same issue with previous 4.19 kernels too, so something has changed in newer kernels.

**Solution**

The script needs some (heavy?) reworking to get its stats under the new interface.

**Comment by rdiez** [comment]
Thanks for the heads-up. I have marked the script as broken.

The trouble is, I have last used zram many years ago and I cannot justify the time it would take to fix the script.
