### ISSUE TITLE
--update does not process --include-Parameters

### ISSUE THREAD

**Issue by heikoh81** [rdiez/Tools#2]
Hi there,

thanks for RDChecksum.pl.
I am a private user and have been looking for a tool like yours for 2 years now, especially in regard to updating exisiting hash-databases only for new or changed file. All tools I checked seem to always recreate the hashes on update, which is no use as I want a hash database to detect bit rot and check consistency on several copies of my files on different hard disks.

I have a quite large digital photo and home video collection (1 TB+), and thought a good way would be to split hash files according to calendar years. All photos are organised in 1 folder with subfolders of holidays and excursions starting with the calendar year, e.g. 2014.08.01.Vacation.Spain. I have 600+ subfolders starting with calendar years.

`/usr/local/bin/rdchecksum.pl --create --checksum-file=FileChecksums_2014.txt --include='/\z'  --include='^2014'^C`

This works, however, I tested updating.

`/usr/local/bin/rdchecksum.pl --update--checksum-file=FileChecksums_2014.txt --include='/\z'  --include='^2014'^C`

Result: All hashes were deleted from hash file.

`Directory count: 966
File      count: 0
New file  count: 0
Removed   count: 3,552
Changed   count: 0
Unchanged count: 0
The old checksum file has been backed up with filename: FileChecksums_2014.txt.previous
`

Is there a way for the tool to consider --include-Parameters on --update?

I can still hash the whole 1 TB-folder, then --update would work correct, but I'm on low-end end consumer hardware, so initial hashing takes quite a while.
Hashing is done on a Raspberry Pi 4, by the way, and is very fast, sometimes as fast as Gigabit can get (95 MB/s).

Great Tool.

Greetings from Germany,
Heiko

**Comment by rdiez** [comment]
> [...]
> `/usr/local/bin/rdchecksum.pl --create --checksum-file=FileChecksums_2014.txt --include='/\z' --include='^2014'^C`

What does ^C at the end mean? Did you press Ctrl+C before copying the command from the terminal?

> [...]
> `/usr/local/bin/rdchecksum.pl --update--checksum-file=FileChecksums_2014.txt --include='/\z' --include='^2014'^C`
> 
> Result: All hashes were deleted from hash file.

I did I quick test with exactly the same arguments above and a couple of small test files, and it did work for me. The --include option is considered during an update.

Could it be the extra ^C at the end?

Best regards,
  rdiez

**Comment by heikoh81** [comment]
Thanks for your answer.
^C results from me copying the command example from putty with STRC+C.

Tried it again, and indeed now everything seems to work as expected.
Don't know what went wrong the other time.

`/usr/local/bin/rdchecksum.pl --update --checksum-file=FileChecksums_2019.txt --include='/\z' --include='^2019'
`

Result:
`Directory count: 987
File      count: 60
New file  count: 60
Removed   count: 16
Changed   count: 0
Unchanged count: 3,536
The old checksum file has been backed up with filename: FileChecksums_2019.txt.previous
`
