### ISSUE TITLE
RDChecksum - Add --checksum-file to --verify

### ISSUE THREAD

**Issue by jsalatiel** [rdiez/Tools#3]
Hi, great tool! Would it be possible add --checksum-file to the verify command?

**Comment by rdiez** [comment]
You can already use --checksum-file=filename together with --verify . Or did you mean something else?

**Comment by jsalatiel** [comment]
Sorry, I must have mistyped something because I was sure I was getting 
```
Error running 'rdchecksum.pl': Option '--verify' takes no arguments.
```
