### ISSUE TITLE
Add support to multiple directories at the sametime

### ISSUE THREAD

**Issue by jsalatiel** [rdiez/Tools#4]
Would it be possible to add an option to accept multiple directories to scan at the same time?

I use rchecksum not only to checksum, but also to verify that my backup tool is correctly detecting the file changes by comparing rdchecksum output with my backup tool output.
It runs great if the backup tool has only one single directory to backup, but when it has more than one the backup tool will always aggregate the changes in the output. It would be nice if I still could get rdchecksum to summarize the count changes for several directories at the sametime.

Thanks!

**Comment by jsalatiel** [comment]
Currently If i try for example:
```rdchecksum.pl --create  /home /data```
it will fail
```Error running 'rdchecksum.pl': Option '--create' takes at most one argument.```

**Comment by rdiez** [comment]
It's not a 5-minute job, so I'll add it to my to-do list.

In the meantime, you can work-around it by placing symlinks to all backup directories into a single directory, and pass that single directory to rdchecksum.pl .

**Comment by rdiez** [comment]
I'm afraid I don't have the time to improve RDChecksum in this respect. I have documented this limitation and the work-around described above in the script itself (in the help text).
