### ISSUE TITLE
RDChecksum: File Format Version 1 Vs. 2

### ISSUE THREAD

**Issue by heikoh81** [rdiez/Tools#5]
Hi,

I have a large checksum file created with rdchecksum.pl 0.72.
After reinstalling my sytem rdchecksum.pl now is 0.83.

When I try to verify with my existing checksum file, I get this error:
The file has an unsupported format version of "1".

Can I fix this by changing the version number from 1 to 2 in my checksum file, or have there been serious changes so that I have to recreate my checksum file?
This is the structure of my checksum file:

```
RDChecksum - list of checksums - file format version 1

# Warning: The filename sorting order will probably be unexpected for humans,
# like this sorted sequence: 'Z', 'a', 'ñ'.

2016-04-19T19:55:06.000	CRC-32	458032A5	8,084	file1.txt
2017-11-18T12:44:52.000	CRC-32	4CFC6556	9,493,501	file2.txt
```

Greetings,
Heiko

**Comment by rdiez** [comment]
There is a file format compatibility break between script versions 0.76
and 0.77 (released in September 2022).

The checksum list file format version was increased from 1 to 2, as a new column
with the checksum type was added.

No backwards compatibility is implemented. If you want to use old checksum list files
with format version 1, you will have to stay with script version 0.76, which can be downloaded from this location:

https://github.com/rdiez/Tools/blob/581291de1c4758bd1b88d57e92dd414401785640/RDChecksum/rdchecksum.pl

**Comment by heikoh81** [comment]
This is very strange, because I have script versions 0.72 and 0.71 on my 2 raspberries, and the second column in my FileChecksums.txt-file says CRC-32 (see my code in my 1st post above).

Thus, I tried changing
`RDChecksum - list of checksums - file format version 1`
to
`RDChecksum - list of checksums - file format version 2`

and updating did work (after backing up the old checksum file, of course, just to be sure).
rdchecksum displayed the number of files that were removed, the number of updated files and the total number of files.

I did check other checksum files with file format version 1, and they all do have CRC-32 as the second column.
So maybe the fastest solution to work with script version 0.82 is to bump file format version to 2?

**Comment by rdiez** [comment]
I think you can probably manually "upgrade" your files like that.

The newer script versions may use the new "Adler-32" method, which will confuse the older version.

There is another little change: empty files (0 bytes long) now have "none" as the checksum type and value. If your old list file recorded any empty files, they will fail for that reason.

**Comment by rdiez** [comment]
I'm closing this now, as I think you have enough information on this. If you need any further help, drop me a line.

**Comment by heikoh81** [comment]
Thanks, yes, my problem is solved.
I don't think I have any 0-byte-files, and if so, they will get a checksom of "none" on the next update.

**Comment by heikoh81** [comment]
> I think you can probably manually "upgrade" your files like that.
> 
> The newer script versions may use the new "Adler-32" method, which will confuse the older version.
> 
> There is another little change: empty files (0 bytes long) now have "none" as the checksum type and value. If your old list file recorded any empty files, they will fail for that reason.

Just an update to complete this Issue:
I manually updated version number from 1 to 2.
Indeed I had several empty files.
As expected, they were reported as checksum mismatch.
I then deleted those lines in the checksum file manually and ran an update.
Now the checksum file is up-to-date with "none".

**Comment by rdiez** [comment]
OK, thanks for the confirmation.
