### ISSUE TITLE
RDChecksum - Add --verification-result-path

### ISSUE THREAD

**Issue by heikoh81** [rdiez/Tools#7]
Hi,

would it be possible to add another command line option:
--verification-result-path
to specify where the verification result files get saved?

Reason:
I have a master drive and two rsynced duplicates (one of them remote).
To detect bit rot I need to check my master drive, but also my two duplicates.
However, the verification result folder is also getting rsynced to my duplicates.
When I run verification on the duplicates, the verification result files are saved to the same folder and the "master" verification results are overwritten (as expected).
However, on next rsync, verification result files are overwritten again.

I could use exclude on the rsync, but having an option to specifiy an output folder for the verification results file might come handy not only in my scenario.

Greetings,
Heiko

**Comment by rdiez** [comment]
I just pushed a new version, but I named the new option '--report-file' instead.

Can you confirm that it works for you?

**Comment by heikoh81** [comment]
Thanks for the very fast implementation.
It is working as expected.

I noticed one thing that might be considered, though.
On first try, I only specified a path (without a filename).
This resulted in an error:
```
/usr/local/bin/rdchecksum.pl --verify --report-file=/home/pi/
Error running 'rdchecksum.pl': Cannot create or truncate file "/home/pi/" for writing: Is a directory
```

So maybe, if no filename is specified and only a path is given, the default file name should be used to avoid the error message?

Greetings,
Heiko

**Comment by rdiez** [comment]
I do not actually think that this improvement would be a good idea. It would make the code and documentation more complicated, and it would be a little surprising, as most other tools do not behave like that. If at all, I could implement some --checksum-dir option, where the script could look for such files. But there are only 2 files at the moment (checksum list file and verification report file), so I think it is not actually worth the effort.

**Comment by heikoh81** [comment]
Ok. So I close this issue as the new function is implemented and tested.
Thank you very much.
